name: devel-docker
on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/devel.yml
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/devel.yml

env:
  DOCKER_IMAGE: localhost:5000/github.com/joseluisq/docker-osxcross

jobs:
  docker-debian:
    name: Docker test (debian)
    strategy:
      matrix:
        arch:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-22.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      -
        name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-osxcross-${{ matrix.arch }}-debian-buildx-${{ github.sha }}
          restore-keys: |
            docker-osxcross-${{ matrix.arch }}-debian-buildx-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Docker meta debian
        id: meta_debian
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      -
        name: Build and export to Docker client
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.arch }}
          file: Dockerfile
          load: true
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}
          build-args: |
            VERSION=0.0.0
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.arch }}
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}
          build-args: |
            VERSION=0.0.0
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Inspect image
        run: |
          docker image inspect ${{ env.DOCKER_IMAGE }}:${{ steps.meta_debian.outputs.version }}
      -
        name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE }}:${{ steps.meta_debian.outputs.version }}
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
