name: release-docker
on:
  push:
    tags:
    - 'v1.0.[0-9]+'
    - 'v1.0.[0-9]+-beta.[0-9]+'

jobs:
  docker-image-debian:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Docker meta debian
        id: meta_debian
        uses: docker/metadata-action@v5
        with:
          images: |
            joseluisq/docker-osxcross
            ghcr.io/joseluisq/docker-osxcross
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Prepare Docker envs
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV
      -
        name: Build and push (debian)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: ${{ steps.meta_debian.outputs.tags }}
          build-args: |
            VERSION=${{ env.VERSION }}
