name: release-beta
on:
  push:
    tags:
    - 'v1.0.[0-9]+-beta.[0-9]+'

jobs:
  build-amd64:
    name: osxcross (amd64)
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            joseluisq/docker-osxcross
            ghcr.io/joseluisq/docker-osxcross
          flavor: |
            latest=false
            suffix=-amd64
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{version}}-amd64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          context: .
          platforms: linux/amd64
          file: ./docker/amd64/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  build-arm64:
    name: osxcross (arm64)
    runs-on: ubuntu-22.04-arm
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            joseluisq/docker-osxcross
            ghcr.io/joseluisq/docker-osxcross
          flavor: |
            latest=false
            suffix=-arm64
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{version}}-arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          context: .
          platforms: linux/arm64
          file: ./docker/arm64/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  manifest:
    needs:
      - build-amd64
      - build-arm64
    runs-on: ubuntu-22.04
    steps:
      - name: Set envs
        run: |
          github_ref=${GITHUB_REF#refs/tags/}
          SEMVER=${github_ref##*v}
          echo "SEMVER=${SEMVER}" >> $GITHUB_ENV
          echo $SEMVER
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull all images
        run: |
          docker pull joseluisq/docker-osxcross:$SEMVER-amd64
          docker pull joseluisq/docker-osxcross:$SEMVER-arm64

          docker pull ghcr.io/joseluisq/docker-osxcross:$SEMVER-amd64
          docker pull ghcr.io/joseluisq/docker-osxcross:$SEMVER-arm64
      -
        name: Push semver alias
        run: |
          docker manifest create \
            joseluisq/docker-osxcross:$SEMVER \
              --amend joseluisq/docker-osxcross:$SEMVER-amd64 \
              --amend joseluisq/docker-osxcross:$SEMVER-arm64
          docker manifest push joseluisq/docker-osxcross:$SEMVER

          docker manifest create \
            ghcr.io/joseluisq/docker-osxcross:$SEMVER \
              --amend ghcr.io/joseluisq/docker-osxcross:$SEMVER-amd64 \
              --amend ghcr.io/joseluisq/docker-osxcross:$SEMVER-arm64
          docker manifest push ghcr.io/joseluisq/docker-osxcross:$SEMVER
